import {test,expect} from '@playwright/test';
test('password reset focuses the incorrect field, retains values on network failure and offers explicit login',async({page})=>{
 let posts=0;await page.route('**/api/**',route=>route.fulfill({json:{}}));await page.route('**/api/oauth/reset-password',route=>{posts++;return posts===1?route.abort('failed'):route.fulfill({json:{ok:true}});});
 await page.goto('/auth/password/reset?token=reset-A');const password=page.getByTestId('reset-password-input'),confirm=page.getByLabel('再次輸入新密碼');await password.fill('longpassword');await confirm.fill('different');await confirm.press('Enter');await expect(confirm).toBeFocused();await expect(confirm).toHaveAttribute('aria-invalid','true');await expect(confirm).toHaveAccessibleDescription(/不一致/);expect(posts).toBe(0);
 await confirm.fill('longpassword');await confirm.press('Enter');await expect(page.getByRole('alert')).toBeFocused();await expect(password).toHaveValue('longpassword');await page.getByRole('button',{name:'重設密碼',exact:true}).click();await expect(page.getByRole('heading',{name:'密碼已更新'})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'前往登入'})).toBeFocused();await page.keyboard.press('Enter');await expect(page).toHaveURL(/\/login$/);expect(posts).toBe(2);
});
test('forgot-password request recovers without claiming success for a failed response',async({page})=>{
 let posts=0;await page.route('**/api/**',route=>route.fulfill({json:{}}));await page.route('**/api/oauth/forgot-password',route=>{posts++;return route.fulfill({status:posts===1?503:200,json:posts===1?{}:{ok:true}});});
 await page.goto('/login/forgot');const email=page.getByLabel('電子郵件');await email.fill('user@example.com');await email.press('Enter');await expect(page.getByRole('alert')).toBeFocused();await expect(email).toHaveValue('user@example.com');await page.keyboard.press('Tab');await expect(email).toBeFocused();await email.press('Enter');await expect(page.getByRole('heading',{name:'查看你的信箱'})).toBeFocused();await expect(page.getByText(/已註冊/)).toContainText('將寄至信箱');await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'回登入'})).toBeFocused();expect(posts).toBe(2);
});
